version: '3'
services:
  website:
    build: './frontend'
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_USER_BACKEND=/api/user
      - NEXT_PUBLIC_CONTENT_BACKEND=/api/content
  contents:
    build: './backend/contents'
    ports:
      - "5002:5002"
    depends_on: 
      - db
    environment:
      - MONGO_URI=mongodb://db/microservices
  users:
    build: './backend/users'
    ports:
      - "5001:5001"
    depends_on: 
      - db
    environment:
      - MONGO_URI=mongodb://db/microservices
  db:
    image: mongo
    ports:
      - "27017:27017"

  nginx:
    image: nginx:latest
    ports:
      - "8080:8080"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - website
      - users
      - contents
